### ISSUE TITLE
probable mispelling in multiplayer_game.py

### ISSUE THREAD

**Issue by olofeldre** [HelmerNylen/mkbsc#1]
In multiplayer game I found this code (excerpt). 
```python
if epistemic:
            func = epistemic_functions[epistemic.lower()]
            for state in G.nodes():
                G.node[state]["label"] = func(state)
            
        G.add_node("hidden", shape="none", label="")
        G.add_edge("hidden", self.initial_state)

        if target_states:
            for i in range(len(target_states)):
                if type(target_states[i]) is not State:
                    target_states[i:i+1] = _lookup_by_base(self.states, target_states[i])
            for target_state in target_states:
                G.node[target_state]["shape"] = "doublecircle"
```
The object named G (a digraph from networkx) has no member variable "node". If these two
occurences are not fixed in the sample program, it does not run.  Changing "node" to "nodes" seems
to fix this.

**Comment by HelmerNylen** [comment]
Hello! Fun that this code is being used two years later :)

This behavior seems to have changed in a newer NetworkX version. We wrote this for NetworkX 2.1 and pydot 1.2.4, and back then I believe G.node was an alias for G.nodes (indeed the example works using those versions). It seems G.node has been deprecated since so I've updated the excerpt to work with the newer versions. It should work if you try the latest version.

I have unfortunately forgotten most of the theory since writing the code, so I'm unfit to properly bugtest the library for use with newer versions of python, networkx and pydot. There may very well be other problems that do not arise from simply running the example. If you run into any other issues feel free to tell me (or even submit a pull request of your own)!
